/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    experience: Experience;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    hero: Hero;
    about: About;
    cta: Cta;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  icon: 'pen' | 'grid' | 'bulb';
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  _order?: string | null;
  period: string;
  role: string;
  company: string;
  companyLink?: string | null;
  description?: string | null;
  isCurrent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  slug: string;
  category: string;
  year: string;
  thumbnail?: {
    media?: (number | null) | Media;
    /**
     * Built-in placeholder art used until media is uploaded
     */
    placeholderKey?: ('bank-saqu' | 'banking-app' | 'saas-wireframes' | 'design-system' | 'banking-homepage') | null;
  };
  featured?: boolean | null;
  summary: string;
  metaGrid?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  heroImage?: {
    media?: (number | null) | Media;
    alt?: string | null;
    caption?: string | null;
    showPlaceholder?: boolean | null;
  };
  sections?:
    | (
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            heading?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            closingParagraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            heading?: string | null;
            intro?: string | null;
            style: 'bullet' | 'check' | 'arrow';
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bulletList';
          }
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            heading: string;
            cards?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hmwGrid';
          }
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            /**
             * Heading for the step group (set on the first step only)
             */
            sectionHeading?: string | null;
            stepNumber: number;
            title: string;
            description?: string | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            image?: {
              media?: (number | null) | Media;
              alt?: string | null;
              caption?: string | null;
              showPlaceholder?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepBlock';
          }
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            heading: string;
            leftTitle: string;
            leftItems?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            rightTitle: string;
            rightItems?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            image?: {
              media?: (number | null) | Media;
              alt?: string | null;
              caption?: string | null;
              showPlaceholder?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumn';
          }
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            heading: string;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            calloutTitle: string;
            calloutItems?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'impactCallout';
          }
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            heading: string;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            learningsTitle?: string | null;
            learnings?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            pullQuoteText?: string | null;
            pullQuoteAccent?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reflection';
          }
        | {
            /**
             * Optional section anchor (used by the case-study tab nav)
             */
            anchor?: string | null;
            image?: {
              media?: (number | null) | Media;
              alt?: string | null;
              caption?: string | null;
              showPlaceholder?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
      )[]
    | null;
  nextProjectSlug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  icon?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  _order?: T;
  period?: T;
  role?: T;
  company?: T;
  companyLink?: T;
  description?: T;
  isCurrent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  category?: T;
  year?: T;
  thumbnail?:
    | T
    | {
        media?: T;
        placeholderKey?: T;
      };
  featured?: T;
  summary?: T;
  metaGrid?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  heroImage?:
    | T
    | {
        media?: T;
        alt?: T;
        caption?: T;
        showPlaceholder?: T;
      };
  sections?:
    | T
    | {
        richText?:
          | T
          | {
              anchor?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              closingParagraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bulletList?:
          | T
          | {
              anchor?: T;
              heading?: T;
              intro?: T;
              style?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hmwGrid?:
          | T
          | {
              anchor?: T;
              heading?: T;
              cards?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepBlock?:
          | T
          | {
              anchor?: T;
              sectionHeading?: T;
              stepNumber?: T;
              title?: T;
              description?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?:
                | T
                | {
                    media?: T;
                    alt?: T;
                    caption?: T;
                    showPlaceholder?: T;
                  };
              id?: T;
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              anchor?: T;
              heading?: T;
              leftTitle?: T;
              leftItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rightTitle?: T;
              rightItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?:
                | T
                | {
                    media?: T;
                    alt?: T;
                    caption?: T;
                    showPlaceholder?: T;
                  };
              id?: T;
              blockName?: T;
            };
        impactCallout?:
          | T
          | {
              anchor?: T;
              heading?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              calloutTitle?: T;
              calloutItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        reflection?:
          | T
          | {
              anchor?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              learningsTitle?: T;
              learnings?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              pullQuoteText?: T;
              pullQuoteAccent?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              anchor?: T;
              image?:
                | T
                | {
                    media?: T;
                    alt?: T;
                    caption?: T;
                    showPlaceholder?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  nextProjectSlug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  logoText: string;
  /**
   * Replaces the text logo in the header when set
   */
  logoImage?: (number | null) | Media;
  /**
   * Browser tab icon (PNG/SVG/ICO, ideally square)
   */
  favicon?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    label: string;
    href: string;
    variant: 'dark' | 'outline';
    icon?: ('arrow' | 'whatsapp' | 'email') | null;
    download?: boolean | null;
  };
  footerText?: string | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  backLink: {
    label: string;
    href: string;
    id?: string | null;
  };
  ctaFooter: {
    headline?: string | null;
    subtext?: string | null;
    button: {
      label: string;
      href: string;
      variant: 'dark' | 'outline';
      icon?: ('arrow' | 'whatsapp' | 'email') | null;
      download?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  greeting: string;
  roleHighlight: string;
  bio?: string | null;
  primaryCta: {
    label: string;
    href: string;
    variant: 'dark' | 'outline';
    icon?: ('arrow' | 'whatsapp' | 'email') | null;
    download?: boolean | null;
  };
  secondaryCta: {
    label: string;
    href: string;
    variant: 'dark' | 'outline';
    icon?: ('arrow' | 'whatsapp' | 'email') | null;
    download?: boolean | null;
  };
  socialLinks?:
    | {
        platform: 'linkedin' | 'instagram' | 'email';
        href: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  portrait?: {
    media?: (number | null) | Media;
    alt?: string | null;
    caption?: string | null;
    showPlaceholder?: boolean | null;
  };
  profileCard?: {
    name?: string | null;
    subtitle?: string | null;
    avatarInitial?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  headline: string;
  headlineAccent?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Replaces {years} in paragraphs
   */
  yearsExperience?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: number;
  headline: string;
  headlineAccent?: string | null;
  subtext?: string | null;
  buttons?:
    | {
        label: string;
        href: string;
        variant: 'dark' | 'outline';
        icon?: ('arrow' | 'whatsapp' | 'email') | null;
        download?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logoText?: T;
  logoImage?: T;
  favicon?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        icon?: T;
        download?: T;
      };
  footerText?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  backLink?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaFooter?:
    | T
    | {
        headline?: T;
        subtext?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              icon?: T;
              download?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  greeting?: T;
  roleHighlight?: T;
  bio?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        icon?: T;
        download?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        icon?: T;
        download?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        label?: T;
        id?: T;
      };
  portrait?:
    | T
    | {
        media?: T;
        alt?: T;
        caption?: T;
        showPlaceholder?: T;
      };
  profileCard?:
    | T
    | {
        name?: T;
        subtitle?: T;
        avatarInitial?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  headline?: T;
  headlineAccent?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  yearsExperience?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  headline?: T;
  headlineAccent?: T;
  subtext?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        icon?: T;
        download?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}